# Compiler
GPP = g++

# Compilation flags
GPPFlags = -Wall -Wextra -Werror -Wfatal-errors -std=c++23 -Ofast
Debug = -g

SRC = main.cpp #$(wildcard *.cpp)

HEADER = $(wildcard *.h)

OBJ = $(SRC:.cpp=.o)

# Target Name
TARGET = main.exe

# compile
$(OBJ): $(SRC) $(OBJ)
	$(GPP) $(GPPFlags) $(SRC) -o $(TARGET)

# clean
clean:
	if exist $(TARGET) del $(TARGET)
	if exist *.o del *.o
	@echo "Removed all object files."

all: clean
	$(GPP) $(GPPFlags) main.cpp -o $(TARGET)
	$(GPP) $(GPPFlags) testing.cpp -o testing.exe
